version: '3'

services:
  runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config:/etc/gitlab-runner
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  config:
    driver: vsphere
    driver_opts:
      size: 1mb
