version: '3'

services:

  main:
    image: registry
    ports:
      - "5000:5000"
    networks:
      - proxy
    volumes:
      - main:/var/lib/registry
    deploy:
      resources:
        reservations:
          memory: 100M
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=5000
        - com.df.serviceDomain=${DOMAIN}

volumes:
  main:
    driver: vsphere

networks:
  proxy:
    external: true
