version: '3'

services:

  main:
    image: registry
    #ports:
    #  - "5000:5000"
    networks:
      - proxy
    volumes:
      - main:/var/lib/registry
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    deploy:
      resources:
        reservations:
          memory: 100M
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=5000
        - com.df.serviceDomain=${DOMAIN}
        - com.df.timeoutServer=600

volumes:
  main:
    driver: vsphere
    driver_opts:
      size: 20gb

networks:
  proxy:
    external: true
